version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12

  device-1:
    build: device
    environment:
      - BROKER_HOSTNAME=mosquitto
      - DEVICE_TYPE=TEMPERATURE_SENSOR
      - PYTHONUNBUFFERED=1
    depends_on:
      - gateway

  gateway:
    build: gateway
    environment:
      - MQTT_HOSTNAME=mosquitto
      - KAFKA_BROKER_HOSTNAME=kafka:9092
      - GATEWAY_NAME=gateway1
    depends_on:
      - mosquitto
      - kafka

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    # ports:
    #   - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.3
    # ports:
    #   - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - ALLOW_ANONYMOUS_LOGIN=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

    depends_on:
      - zookeeper

  init-kafka:
    image: docker.io/bitnami/kafka:3.3
    depends_on:
      - kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics.sh --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics.sh --create --topic clean -partitions 3 --bootstrap-server kafka:9092
      kafka-topics.sh --create --topic save -partitions 3 --bootstrap-server kafka:9092
      kafka-topics.sh --create --topic actuate -partitions 3 --bootstrap-server kafka:9092

      echo -e 'Successfully created the following topics:'
      kafka-topics.sh --list --bootstrap-server kafka:9092
      "

  cleanup:
    build: microservices/cleanup
    environment:
      - KAFKA_BROKER_HOSTNAME=kafka:9092

    depends_on:
      - kafka

  actuation:
    build: microservices/actuation
    environment:
      - KAFKA_BROKER_HOSTNAME=kafka:9092

    depends_on:
      - kafka
