version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12

  device-1:
    build: device
    environment:
      - BROKER_HOSTNAME=mosquitto
      - DEVICE_TYPE=TEMPERATURE_SENSOR
      - PYTHONUNBUFFERED=1
    depends_on:
      - gateway

  gateway:
    build: gateway
    environment:
      - MQTT_HOSTNAME=mosquitto
    depends_on:
      - mosquitto
