#Dockerfile

#Docker Python Image
FROM python:3.9.18-slim-bullseye

ARG PYTHONUNBUFFERED=1

# Add python files
ADD ./main.py .
ADD ./requirements.txt .

RUN pip install -r ./requirements.txt

CMD python ./main.py